Homework1
made-ml-in-prod-2021/danidarya pull request #2
Opened 2021-05-09 20:23 UTC by danidarya

Добрый вечер!

В папке data_raw исходные данные и данные для предсказания
В папке src/params находятся датаклассы для параметров.
src/data – функция для загрузки датасета,
src/features  - подготовка данных
src/models -  функции для обучения модели, сохранения ее на диск, предсказания и расчета метрик.
src/train_and_predict_pipeline.py - пайплайн для обучения и предсказания.

Более подробное описание проекта находится в README

2021-05-13 19:51 UTC, happyhooter commented
Извиняюсь за позднее ревью (не сразу заметил себя в ревьюерах).
Небольшое общее замечание: у нас в курсе будет несколько дз, которые нужно будет мерджить в main, поэтому прошу весь код этой домашки положить в папку ml_project.

2021-05-13 19:59 UTC, happyhooter commented on tests/conftest.py
> +    return ["age", "trestbps", "chol", "thalach", "oldpeak"]
Возможно, все эти фикстуры стоит определить со scope="session" (фикстуры сейчас создаются каждый раз, когда происходит обращение к ним). Подробнее про scope можно прочитать в разделе "Спецификация областей(Scope) Fixture" [тут](https://habr.com/ru/post/448786/).

2021-05-13 20:01 UTC, happyhooter commented on tests/test_e2e_pipeline.py
> +    )
Возможно, данный код стоит выделить в фикстуру

2021-05-13 20:04 UTC, happyhooter commented
В остальном вопросов не имею. С самооценкой согласен!

2021-05-13 21:07 UTC, danidarya commented on tests/conftest.py
> +    return ["age", "trestbps", "chol", "thalach", "oldpeak"]
Исправила.

2021-05-13 21:07 UTC, danidarya commented on tests/test_e2e_pipeline.py
> +    )
Сделала. И проект в папку положила. Спасибо за ревью.

2021-05-23 14:08 UTC, merged

2021-05-23 14:35 UTC, kindofman requested changes

2021-05-23 14:35 UTC, kindofman commented on ml_project/notebooks/EDA.ipynb
> +    "data = pd.read_csv('data/heart.csv')"
Просьба поправить путь. И другие ячейки, если где-то еще не запускается.

<img width="874" alt="Снимок экрана 2021-05-23 в 16 11 14" src="https://user-images.githubusercontent.com/43539680/119261807-b2fea280-bbe1-11eb-823d-819549dfe3ac.png">

2021-05-23 15:14 UTC, danidarya commented on ml_project/notebooks/EDA.ipynb
> +    "data = pd.read_csv('data/heart.csv')"
Добрый день .Поправила. У меня почему-то прозошел merge этого pull request, когда делала merge по второму проверенному домашнему заданию. Подскажите, пожалуйста, как можно это исправить.

2021-05-23 19:19 UTC, kindofman commented
Хорошая работа.

28 баллов.